### ISSUE TITLE
Greenhorn Problems with the installation

### ISSUE THREAD

**Issue by petermartinberg** [dolphinoracle/lum-qt-appimage#1]
Hello dolphinoracle,

I wanted to install the tool and followed your instructions.
I've downloaded the zip file, extracted it to the folder where I also downloaded the iso-File , opened a terminal out of this window and copied your command run with "sudo ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage".

Unfortunately it gives the following result:
`petemount@petemount-System-Product-Name:~/Downloads/MX Linux $ sudo ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage
[sudo] Passwort für petemount: 
sudo: ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage: Befehl nicht gefunden
petemount@petemount-System-Product-Name:~/Downloads/MX Linux $ 
`
It says simply "Command not found".

Do you have any idea whats wrong an why it doesn't  install on my Ubuntu System 20.4.

Thank you very much in advance.

Kind regards,
petemount

**Comment by dolphinoracle** [comment]
When you unzipped maybe there is a sun folder?

Anyway the command should be

sudo full/path/to/app image

**Comment by petermartinberg** [comment]
As I'm a german I don't know, what you mean with a "sun Folder" 

I have unzipped the file into a separate foldeŕ and then I go into that folder and open a terminal out of it where I type
`sudo ./live-usb-maker-qt-21.11.glibc2.28-x86-64.AppImage` and it always ends with a command not found. I don't understand, why this isn't working. It's a miracle for me.

**Comment by dolphinoracle** [comment]
My apologize I meant "some" folder.

there is a typing error.  the "command not found" means that something
typed is wrong.

sudo ./live-usb-maker-qt-21.11.glibc2.28-x86_64

**Comment by petermartinberg** [comment]
Well, I have downloaded it again, copied the zip file to separate folder, opened a terminal out of that folder and 
copied your command "sudo ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage" and let run it but nothing changed. It always ends with "command not fund"
`petemount@petemount-System-Product-Name:~/Downloads/MX-Linux-Usbstick-Programm$ sudo ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage
[sudo] Passwort für petemount: 
sudo: ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage: Befehl nicht gefunden
petemount@petemount-System-Product-Name:~/Downloads/MX-Linux-Usbstick-Programm$ 
`

**Comment by dolphinoracle** [comment]
instead of ./  go ahead and type out the full path.

make sure the that appimage is still executable.

**Comment by petermartinberg** [comment]
Hello dolphinoracle,
the problem was that the appimage-File wasn't executable. So I first had to make it executable and now it works fine.
Thank you for your help. I keep that in mind for future AppImages.
Kind regards,
petemount
