### ISSUE TITLE
minor inconvenience, just a missing .

### ISSUE THREAD

**Issue by jacklominious** [dolphinoracle/lum-qt-appimage#5]
in the live-usb-maker-qt-21.7 appimage Pre-release description:

run with "sudo ./live-usb-maker-qt-21.11glibc2.28-x86_64.AppImage" misses a . between 21.11 and glibc

should be:

run with "sudo ./live-usb-maker-qt-21.11.glibc2.28-x86_64.AppImage"

to run ;-)

**Comment by dolphinoracle** [comment]
fixed thanks
