### ISSUE TITLE
Please update the docs or add somewhere else the "sudo" requirement

### ISSUE THREAD

**Issue by lorn10** [dolphinoracle/lum-qt-appimage#6]
Hi all

It looks that the AppImages are requiring `sudo`. Please note this somewhere for the noobs and beginners. Thanks! :+1: 

When started normally there appears otherwise the following error message:

`x-terminal-emulator: symbol lookup error: /lib/x86_64-linux-gnu/libKF5GuiAddons.so.5: undefined symbol: wl_proxy_marshal_flags`

This was tested under **Kubuntu 22.04 LTS** and USB Maker 21.11.

**Edit**: The basic `dd` option seems to work while the "live" one doesn't. Seems to be a `libgio-2.0.so` related incompatibility:
`mx-viewer: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full`

**Comment by dolphinoracle** [comment]
the sudo requirement is literally in the release note.  

[live-usb-maker-qt-21.11 appimage](https://github.com/dolphinoracle/lum-qt-appimage/releases/tag/21.11) [Latest](https://github.com/dolphinoracle/lum-qt-appimage/releases/latest)

live-usb-maker-qt-21.7 appimage Pre-release

Updated and tested on
ubuntu 20.04
Debian 11.
Fedora 35
manjaro 21.1

Does not work on solus 4.3 at this time.

Download the zip file containing the AppImage, extract to a folder, enter that folder, and use

run with "sudo ./live-usb-maker-qt-21.11.glibc2.28-x86_64.AppImage"

to run the app.

Not all features have been tested, but making a basic "full featured" MX/antiX live-usb works ok.

Tested on fedora, manjaro, pclinuxos and ubuntu.

**Comment by lorn10** [comment]
Thanks for the fast answer. Yeah, but a note at the download location would be even better. :wink: 

Whatever, this tool does work as of 2024 only partially on 22.04 LTS because of the `libgio-2.0.so`  issue and it seems to be also not no longer compliant to 20.04 LTS. The "live USB mode" is broken also there. Probably I should open a new bug report about that. Will see.
